---
- name: "rust | Check if cargo is installed"
  ansible.builtin.command: "cargo"
  register: cargo_exists
  ignore_errors: true
  changed_when: false

- name: "Install"
  community.general.homebrew:
    name: rust
    state: present
  when: cargo_exists is failed
