---
- name: DotFiles Config
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yaml
      tags:
        - always

  roles:
    # update & configure system
    - system
    # networking foundation
    - curl
    - ssh
    - wget
    # git config
    - git
    # build tools
    - gcc
    - podman
    - rust
    # fonts
    - nerd_fonts
    # terminal and cli tools
    - alacritty
    - bat
    - bottom
    - eza
    - fd
    - fzf
    - htop
    - jq
    - k9s
    - mtr
    - neofetch
    - ripgrep
    - tmux
    - zoxide
    - trunk
    - zsh
    # nvim setup
    - lazygit
    - neovim
    # IDEs
    - visual_studio_code
    - pre_commit
    # password manager
    - keepassxc
    # fun
    - asciiquarium
    - cmatrix
    - spotify
    - toipe

  tasks:
    - name: Look for addon_roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or addon_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display addon_roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run addon_roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
