---
- name: Import tasks for macOS
  ansible.builtin.import_tasks: macos.yaml
  when: ansible_os_family == 'Darwin'

- name: Import tasks for Linux
  ansible.builtin.import_tasks: linux.yaml
  when: ansible_system == 'Linux'

- name: Update hooks
  ansible.builtin.command: pre-commit autoupdate
  register: output
  changed_when: output.rc != 0

- name: Install hooks
  ansible.builtin.command: pre-commit install
  register: output
  changed_when: output.rc != 0
