---
- name: Install
  ansible.builtin.package:
    name: keepassxc
  become: true

- name: Create config directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/keepassxc"
    state: directory
    mode: "0700"

- name: Copy config
  ansible.builtin.template:
    src: keepassxc.ini
    dest: "{{ ansible_env.HOME }}/.config/keepassxc/keepassxc.ini"
    mode: "0600"
