---
- name: "Install"
  community.general.homebrew_cask:
    name: keepassxc
    state: present

- name: "create config directory if it does not exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/Users/{{ ansible_env.USER }}/Library/Application Support/KeePassXC"
    - "/Users/{{ ansible_env.USER }}/Library/Caches/KeePassXC"

- name: "Copy config"
  ansible.builtin.template:
    src: keepassxc.ini.j2
    dest: "{{ item }}/keepassxc.ini"
  loop:
    - "/Users/{{ ansible_env.USER }}/Library/Application Support/KeePassXC"
    - "/Users/{{ ansible_env.USER }}/Library/Caches/KeePassXC"
