---
- name: "Install"
  community.general.homebrew_cask:
    name: keepassxc
    state: present

- name: "Copy config"
  ansible.builtin.template:
    src: keepassxc.ini.j2
    dest: "/Users/{{ ansible_env.USER }}/Library/Application Support/KeePassXC/keepassxc.ini "
