---
- name: System | Update Homebrew Repositories and Upgrade Packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Set systems languages
  community.general.osx_defaults:
    key: AppleLanguages
    type: array
    value:
      - en
      - de

- name: Check if Rosetta 2 is installed
  ansible.builtin.command: /usr/bin/pgrep -q oahd
  register: oahd
  ignore_errors: true
  changed_when: false

- name: Install Rosetta 2
  ansible.builtin.command: sudo softwareupdate --install-rosetta --agree-to-license
  register: result
  when: oahd.rc != 0
  changed_when: result.rc != 0
