---
- name: Import tasks for macOS
  ansible.builtin.import_tasks: macos.yaml
  when: ansible_os_family == 'Darwin'

- name: git | Set global Git user name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git.username }}"

- name: git | Set global Git email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git.email }}"

- name: git | Set dotfiles Git user name
  community.general.git_config:
    name: user.name
    scope: local
    value: "{{ git_dotfiles.username }}"
    repo: "{{ playbook_dir }}"

- name: git | Set dotfiles Git email
  community.general.git_config:
    name: user.email
    scope: local
    value: "{{ git_dotfiles.email }}"
    repo: "{{ playbook_dir }}"

- name: Create home home_directory
  ansible.builtin.file:
    dest: "{{ git.home_directory }}"
    state: directory
    mode: "0700"

- name: Clone and update repositories
  # this task has no idempotency by design, since I want to update the repos.
  # (https://ansible.readthedocs.io/projects/lint/rules/latest/)
  # noqa: latest
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "{{ git.home_directory }}/{{ item | replace('%20', ' ') | regex_search('[\\w\\s\\.-]+[\\/]+[\\w\\.-]+(?=\\.git|$)') | replace('.git', '') }}"
    clone: true
    update: true
    accept_hostkey: true
  retries: 5
  delay: 5
  with_items: "{{ git.repositories }}"
