---
- name: Install
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present

- name: Setup settings directory
  ansible.builtin.file:
    path: /Users/{{ ansible_env.USER }}/Library/Application Support/Code/User
    state: directory
    mode: "0700"

- name: Copy settings
  ansible.builtin.template:
    src: settings.json
    dest: /Users/{{ ansible_env.USER }}/Library/Application Support/Code/User/settings.json
    mode: "0600"

- name: Create symlink for key bindings config
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/dotfiles/roles/visual_studio_code/files/keybindings.json"
    dest: /Users/{{ ansible_env.USER }}/Library/Application Support/Code/User/keybindings.json
    state: link
