---
- name: Import tasks for macOS
  ansible.builtin.import_tasks: macos.yaml
  when: ansible_os_family == 'Darwin'

- name: Import tasks for Linux
  ansible.builtin.import_tasks: linux.yaml
  when: ansible_system == 'Linux'

- name: Gather extensions defined in dotfiles
  ansible.builtin.command: cat {{ ansible_env.HOME }}/dotfiles/roles/visual_studio_code/files/extensions
  register: extensions
  changed_when: extensions.rc != 0

- name: Gather installed extensions
  ansible.builtin.command: code --list-extensions | sort
  register: installed
  changed_when: installed.rc != 0

- name: Calculate missing extensions
  ansible.builtin.set_fact:
    missing_extensions: "{{ extensions.stdout_lines | difference(installed.stdout_lines) }}"

- name: Print status
  ansible.builtin.debug:
    msg: "Found {{ missing_extensions | length }} missing VSCode extensions: {{ missing_extensions }}"

- name: Install missing extensions
  ansible.builtin.command: code --install-extension {{ item }}
  with_items: "{{ missing_extensions }}"
  when: missing_extensions | length > 0
  retries: 5
  changed_when: missing_extensions | length > 0

- name: Generate updated extensions list
  ansible.builtin.command: code --list-extensions | sort
  register: updated
  changed_when: updated.rc != 0

- name: Update extensions list in dotfiles
  ansible.builtin.copy:
    content: "{{ updated.stdout }}\n"
    dest: "{{ ansible_env.HOME }}/dotfiles/roles/visual_studio_code/files/extensions"
    mode: "0600"
